//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка на работы.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [Caption("Заявка на работы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "Важность as \'Важность\'",
            "КодЗаявки as \'Код заявки\'",
            "КодСотрудника as \'Код сотрудника\'",
            "КодКонтрагента as \'Код контрагента\'"})]
    [View("ЗаявкаL", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "Важность as \'Важность\'",
            "КодЗаявки as \'Код заявки\'",
            "КодСотрудника as \'Код сотрудника\'",
            "КодКонтрагента as \'Код контрагента\'"})]
    [View("ЗаявкаНаРаботыE", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "Важность as \'Важность\'"})]
    [View("ЗаявкаНаРаботыL", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "Важность as \'Важность\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерЗаявки;
        
        private string fКодСотрудника;
        
        private int fКодЗаявки;
        
        private string fВажность;
        
        private string fКодКонтрагента;
        
        private IIS.7.Контрагент fКонтрагент;
        
        private IIS.7.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// Важность.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Важность CustomAttributes)

        // *** End programmer edit section *** (Заявка.Важность CustomAttributes)
        [StrLen(255)]
        public virtual string Важность
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Важность Get start)

                // *** End programmer edit section *** (Заявка.Важность Get start)
                string result = this.fВажность;
                // *** Start programmer edit section *** (Заявка.Важность Get end)

                // *** End programmer edit section *** (Заявка.Важность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Важность Set start)

                // *** End programmer edit section *** (Заявка.Важность Set start)
                this.fВажность = value;
                // *** Start programmer edit section *** (Заявка.Важность Set end)

                // *** End programmer edit section *** (Заявка.Важность Set end)
            }
        }
        
        /// <summary>
        /// КодЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.КодЗаявки CustomAttributes)

        // *** End programmer edit section *** (Заявка.КодЗаявки CustomAttributes)
        public virtual int КодЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.КодЗаявки Get start)

                // *** End programmer edit section *** (Заявка.КодЗаявки Get start)
                int result = this.fКодЗаявки;
                // *** Start programmer edit section *** (Заявка.КодЗаявки Get end)

                // *** End programmer edit section *** (Заявка.КодЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.КодЗаявки Set start)

                // *** End programmer edit section *** (Заявка.КодЗаявки Set start)
                this.fКодЗаявки = value;
                // *** Start programmer edit section *** (Заявка.КодЗаявки Set end)

                // *** End programmer edit section *** (Заявка.КодЗаявки Set end)
            }
        }
        
        /// <summary>
        /// КодКонтрагента.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.КодКонтрагента CustomAttributes)

        // *** End programmer edit section *** (Заявка.КодКонтрагента CustomAttributes)
        [StrLen(255)]
        public virtual string КодКонтрагента
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.КодКонтрагента Get start)

                // *** End programmer edit section *** (Заявка.КодКонтрагента Get start)
                string result = this.fКодКонтрагента;
                // *** Start programmer edit section *** (Заявка.КодКонтрагента Get end)

                // *** End programmer edit section *** (Заявка.КодКонтрагента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.КодКонтрагента Set start)

                // *** End programmer edit section *** (Заявка.КодКонтрагента Set start)
                this.fКодКонтрагента = value;
                // *** Start programmer edit section *** (Заявка.КодКонтрагента Set end)

                // *** End programmer edit section *** (Заявка.КодКонтрагента Set end)
            }
        }
        
        /// <summary>
        /// КодСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.КодСотрудника CustomAttributes)

        // *** End programmer edit section *** (Заявка.КодСотрудника CustomAttributes)
        [StrLen(255)]
        public virtual string КодСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.КодСотрудника Get start)

                // *** End programmer edit section *** (Заявка.КодСотрудника Get start)
                string result = this.fКодСотрудника;
                // *** Start programmer edit section *** (Заявка.КодСотрудника Get end)

                // *** End programmer edit section *** (Заявка.КодСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.КодСотрудника Set start)

                // *** End programmer edit section *** (Заявка.КодСотрудника Set start)
                this.fКодСотрудника = value;
                // *** Start programmer edit section *** (Заявка.КодСотрудника Set end)

                // *** End programmer edit section *** (Заявка.КодСотрудника Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.НомерЗаявки CustomAttributes)

        // *** End programmer edit section *** (Заявка.НомерЗаявки CustomAttributes)
        [StrLen(255)]
        public virtual string НомерЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.НомерЗаявки Get start)

                // *** End programmer edit section *** (Заявка.НомерЗаявки Get start)
                string result = this.fНомерЗаявки;
                // *** Start programmer edit section *** (Заявка.НомерЗаявки Get end)

                // *** End programmer edit section *** (Заявка.НомерЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.НомерЗаявки Set start)

                // *** End programmer edit section *** (Заявка.НомерЗаявки Set start)
                this.fНомерЗаявки = value;
                // *** Start programmer edit section *** (Заявка.НомерЗаявки Set end)

                // *** End programmer edit section *** (Заявка.НомерЗаявки Set end)
            }
        }
        
        /// <summary>
        /// Заявка на работы.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Заявка.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.7.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Контрагент Get start)

                // *** End programmer edit section *** (Заявка.Контрагент Get start)
                IIS.7.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (Заявка.Контрагент Get end)

                // *** End programmer edit section *** (Заявка.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Контрагент Set start)

                // *** End programmer edit section *** (Заявка.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Заявка.Контрагент Set end)

                // *** End programmer edit section *** (Заявка.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Заявка на работы.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заявка.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.7.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Сотрудник Get start)

                // *** End programmer edit section *** (Заявка.Сотрудник Get start)
                IIS.7.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заявка.Сотрудник Get end)

                // *** End programmer edit section *** (Заявка.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Сотрудник Set start)

                // *** End programmer edit section *** (Заявка.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заявка.Сотрудник Set end)

                // *** End programmer edit section *** (Заявка.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.7.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.7.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаНаРаботыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаРаботыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаРаботыE", typeof(IIS.7.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаНаРаботыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаРаботыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаРаботыL", typeof(IIS.7.Заявка));
                }
            }
        }
    }
}
