//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись регистра.
    /// </summary>
    // *** Start programmer edit section *** (Запись CustomAttributes)

    // *** End programmer edit section *** (Запись CustomAttributes)
    [AutoAltered()]
    [Caption("Запись регистра")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "ВремяОкончания as \'Время окончания\'",
            "ВремяНачала as \'Время начала\'",
            "Дата as \'Дата\'",
            "КодЗаявки as \'Код заявки\'",
            "КодРегистра as \'Код регистра\'",
            "КодЗаписи as \'Код записи\'"})]
    [View("ЗаписьL", new string[] {
            "ВремяОкончания as \'Время окончания\'",
            "ВремяНачала as \'Время начала\'",
            "Дата as \'Дата\'",
            "КодЗаявки as \'Код заявки\'",
            "КодРегистра as \'Код регистра\'",
            "КодЗаписи as \'Код записи\'"})]
    [View("ЗаписьРегистраE", new string[] {
            "ВремяОкончания as \'Время окончания\'",
            "ВремяНачала as \'Время начала\'",
            "Дата as \'Дата\'"})]
    [View("ЗаписьРегистраL", new string[] {
            "ВремяОкончания as \'Время окончания\'",
            "ВремяНачала as \'Время начала\'",
            "Дата as \'Дата\'"})]
    public class Запись : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fВремяНачала;
        
        private string fВремяОкончания;
        
        private int fКодРегистра;
        
        private int fКодЗаявки;
        
        private int fКодЗаписи;
        
        private IIS.7.Заявка fЗаявка;
        
        private IIS.7.Регистр fРегистр;
        
        // *** Start programmer edit section *** (Запись CustomMembers)

        // *** End programmer edit section *** (Запись CustomMembers)

        
        /// <summary>
        /// ВремяНачала.
        /// </summary>
        // *** Start programmer edit section *** (Запись.ВремяНачала CustomAttributes)

        // *** End programmer edit section *** (Запись.ВремяНачала CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяНачала
        {
            get
            {
                // *** Start programmer edit section *** (Запись.ВремяНачала Get start)

                // *** End programmer edit section *** (Запись.ВремяНачала Get start)
                string result = this.fВремяНачала;
                // *** Start programmer edit section *** (Запись.ВремяНачала Get end)

                // *** End programmer edit section *** (Запись.ВремяНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.ВремяНачала Set start)

                // *** End programmer edit section *** (Запись.ВремяНачала Set start)
                this.fВремяНачала = value;
                // *** Start programmer edit section *** (Запись.ВремяНачала Set end)

                // *** End programmer edit section *** (Запись.ВремяНачала Set end)
            }
        }
        
        /// <summary>
        /// ВремяОкончания.
        /// </summary>
        // *** Start programmer edit section *** (Запись.ВремяОкончания CustomAttributes)

        // *** End programmer edit section *** (Запись.ВремяОкончания CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОкончания
        {
            get
            {
                // *** Start programmer edit section *** (Запись.ВремяОкончания Get start)

                // *** End programmer edit section *** (Запись.ВремяОкончания Get start)
                string result = this.fВремяОкончания;
                // *** Start programmer edit section *** (Запись.ВремяОкончания Get end)

                // *** End programmer edit section *** (Запись.ВремяОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.ВремяОкончания Set start)

                // *** End programmer edit section *** (Запись.ВремяОкончания Set start)
                this.fВремяОкончания = value;
                // *** Start programmer edit section *** (Запись.ВремяОкончания Set end)

                // *** End programmer edit section *** (Запись.ВремяОкончания Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Дата CustomAttributes)

        // *** End programmer edit section *** (Запись.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Дата Get start)

                // *** End programmer edit section *** (Запись.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Запись.Дата Get end)

                // *** End programmer edit section *** (Запись.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Дата Set start)

                // *** End programmer edit section *** (Запись.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Запись.Дата Set end)

                // *** End programmer edit section *** (Запись.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (Запись.КодЗаписи CustomAttributes)

        // *** End programmer edit section *** (Запись.КодЗаписи CustomAttributes)
        public virtual int КодЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Запись.КодЗаписи Get start)

                // *** End programmer edit section *** (Запись.КодЗаписи Get start)
                int result = this.fКодЗаписи;
                // *** Start programmer edit section *** (Запись.КодЗаписи Get end)

                // *** End programmer edit section *** (Запись.КодЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.КодЗаписи Set start)

                // *** End programmer edit section *** (Запись.КодЗаписи Set start)
                this.fКодЗаписи = value;
                // *** Start programmer edit section *** (Запись.КодЗаписи Set end)

                // *** End programmer edit section *** (Запись.КодЗаписи Set end)
            }
        }
        
        /// <summary>
        /// КодЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Запись.КодЗаявки CustomAttributes)

        // *** End programmer edit section *** (Запись.КодЗаявки CustomAttributes)
        public virtual int КодЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Запись.КодЗаявки Get start)

                // *** End programmer edit section *** (Запись.КодЗаявки Get start)
                int result = this.fКодЗаявки;
                // *** Start programmer edit section *** (Запись.КодЗаявки Get end)

                // *** End programmer edit section *** (Запись.КодЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.КодЗаявки Set start)

                // *** End programmer edit section *** (Запись.КодЗаявки Set start)
                this.fКодЗаявки = value;
                // *** Start programmer edit section *** (Запись.КодЗаявки Set end)

                // *** End programmer edit section *** (Запись.КодЗаявки Set end)
            }
        }
        
        /// <summary>
        /// КодРегистра.
        /// </summary>
        // *** Start programmer edit section *** (Запись.КодРегистра CustomAttributes)

        // *** End programmer edit section *** (Запись.КодРегистра CustomAttributes)
        public virtual int КодРегистра
        {
            get
            {
                // *** Start programmer edit section *** (Запись.КодРегистра Get start)

                // *** End programmer edit section *** (Запись.КодРегистра Get start)
                int result = this.fКодРегистра;
                // *** Start programmer edit section *** (Запись.КодРегистра Get end)

                // *** End programmer edit section *** (Запись.КодРегистра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.КодРегистра Set start)

                // *** End programmer edit section *** (Запись.КодРегистра Set start)
                this.fКодРегистра = value;
                // *** Start programmer edit section *** (Запись.КодРегистра Set end)

                // *** End programmer edit section *** (Запись.КодРегистра Set end)
            }
        }
        
        /// <summary>
        /// Запись регистра.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Заявка CustomAttributes)

        // *** End programmer edit section *** (Запись.Заявка CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявка"})]
        [NotNull()]
        public virtual IIS.7.Заявка Заявка
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Заявка Get start)

                // *** End programmer edit section *** (Запись.Заявка Get start)
                IIS.7.Заявка result = this.fЗаявка;
                // *** Start programmer edit section *** (Запись.Заявка Get end)

                // *** End programmer edit section *** (Запись.Заявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Заявка Set start)

                // *** End programmer edit section *** (Запись.Заявка Set start)
                this.fЗаявка = value;
                // *** Start programmer edit section *** (Запись.Заявка Set end)

                // *** End programmer edit section *** (Запись.Заявка Set end)
            }
        }
        
        /// <summary>
        /// Запись регистра.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Регистр CustomAttributes)

        // *** End programmer edit section *** (Запись.Регистр CustomAttributes)
        [PropertyStorage(new string[] {
                "Регистр"})]
        [NotNull()]
        public virtual IIS.7.Регистр Регистр
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Регистр Get start)

                // *** End programmer edit section *** (Запись.Регистр Get start)
                IIS.7.Регистр result = this.fРегистр;
                // *** Start programmer edit section *** (Запись.Регистр Get end)

                // *** End programmer edit section *** (Запись.Регистр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Регистр Set start)

                // *** End programmer edit section *** (Запись.Регистр Set start)
                this.fРегистр = value;
                // *** Start programmer edit section *** (Запись.Регистр Set end)

                // *** End programmer edit section *** (Запись.Регистр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.7.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьL", typeof(IIS.7.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьРегистраE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьРегистраE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьРегистраE", typeof(IIS.7.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьРегистраL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьРегистраL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьРегистраL", typeof(IIS.7.Запись));
                }
            }
        }
    }
}
