//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контрагент.
    /// </summary>
    // *** Start programmer edit section *** (Контрагент CustomAttributes)

    // *** End programmer edit section *** (Контрагент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрагентE", new string[] {
            "Наименование as \'Наименование\'",
            "Организация as \'Организация\'"})]
    [View("КонтрагентL", new string[] {
            "Наименование as \'Наименование\'",
            "Организация as \'Организация\'"})]
    public class Контрагент : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКонтрагента;
        
        private string fНаименование;
        
        private string fДоговор;
        
        private string fОрганизация;
        
        // *** Start programmer edit section *** (Контрагент CustomMembers)

        // *** End programmer edit section *** (Контрагент CustomMembers)

        
        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Договор CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Договор CustomAttributes)
        [StrLen(255)]
        public virtual string Договор
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Договор Get start)

                // *** End programmer edit section *** (Контрагент.Договор Get start)
                string result = this.fДоговор;
                // *** Start programmer edit section *** (Контрагент.Договор Get end)

                // *** End programmer edit section *** (Контрагент.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Договор Set start)

                // *** End programmer edit section *** (Контрагент.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (Контрагент.Договор Set end)

                // *** End programmer edit section *** (Контрагент.Договор Set end)
            }
        }
        
        /// <summary>
        /// КодКонтрагента.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.КодКонтрагента CustomAttributes)

        // *** End programmer edit section *** (Контрагент.КодКонтрагента CustomAttributes)
        public virtual int КодКонтрагента
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.КодКонтрагента Get start)

                // *** End programmer edit section *** (Контрагент.КодКонтрагента Get start)
                int result = this.fКодКонтрагента;
                // *** Start programmer edit section *** (Контрагент.КодКонтрагента Get end)

                // *** End programmer edit section *** (Контрагент.КодКонтрагента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.КодКонтрагента Set start)

                // *** End programmer edit section *** (Контрагент.КодКонтрагента Set start)
                this.fКодКонтрагента = value;
                // *** Start programmer edit section *** (Контрагент.КодКонтрагента Set end)

                // *** End programmer edit section *** (Контрагент.КодКонтрагента Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Наименование CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Наименование Get start)

                // *** End programmer edit section *** (Контрагент.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Контрагент.Наименование Get end)

                // *** End programmer edit section *** (Контрагент.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Наименование Set start)

                // *** End programmer edit section *** (Контрагент.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Контрагент.Наименование Set end)

                // *** End programmer edit section *** (Контрагент.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Организация.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Организация CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Организация CustomAttributes)
        [StrLen(255)]
        public virtual string Организация
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Организация Get start)

                // *** End programmer edit section *** (Контрагент.Организация Get start)
                string result = this.fОрганизация;
                // *** Start programmer edit section *** (Контрагент.Организация Get end)

                // *** End programmer edit section *** (Контрагент.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Организация Set start)

                // *** End programmer edit section *** (Контрагент.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (Контрагент.Организация Set end)

                // *** End programmer edit section *** (Контрагент.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрагентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентE", typeof(IIS.7.Контрагент));
                }
            }
            
            /// <summary>
            /// "КонтрагентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентL", typeof(IIS.7.Контрагент));
                }
            }
        }
    }
}
