//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр сведений.
    /// </summary>
    // *** Start programmer edit section *** (Регистр CustomAttributes)

    // *** End programmer edit section *** (Регистр CustomAttributes)
    [AutoAltered()]
    [Caption("Регистр сведений")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрE", new string[] {
            "КодРегистра as \'Код регистра\'",
            "Наименование as \'Наименование\'",
            "Периодичность as \'Периодичность\'"})]
    [View("РегистрL", new string[] {
            "КодРегистра as \'Код регистра\'",
            "Наименование as \'Наименование\'",
            "Периодичность as \'Периодичность\'"})]
    [View("РегистрСведенийE", new string[] {
            "Наименование as \'Наименование\'",
            "Периодичность as \'Периодичность\'"})]
    [View("РегистрСведенийL", new string[] {
            "Наименование as \'Наименование\'",
            "Периодичность as \'Периодичность\'"})]
    public class Регистр : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодРегистра;
        
        private string fПериодичность;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Регистр CustomMembers)

        // *** End programmer edit section *** (Регистр CustomMembers)

        
        /// <summary>
        /// КодРегистра.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.КодРегистра CustomAttributes)

        // *** End programmer edit section *** (Регистр.КодРегистра CustomAttributes)
        public virtual int КодРегистра
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.КодРегистра Get start)

                // *** End programmer edit section *** (Регистр.КодРегистра Get start)
                int result = this.fКодРегистра;
                // *** Start programmer edit section *** (Регистр.КодРегистра Get end)

                // *** End programmer edit section *** (Регистр.КодРегистра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.КодРегистра Set start)

                // *** End programmer edit section *** (Регистр.КодРегистра Set start)
                this.fКодРегистра = value;
                // *** Start programmer edit section *** (Регистр.КодРегистра Set end)

                // *** End programmer edit section *** (Регистр.КодРегистра Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Наименование CustomAttributes)

        // *** End programmer edit section *** (Регистр.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Наименование Get start)

                // *** End programmer edit section *** (Регистр.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Регистр.Наименование Get end)

                // *** End programmer edit section *** (Регистр.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Наименование Set start)

                // *** End programmer edit section *** (Регистр.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Регистр.Наименование Set end)

                // *** End programmer edit section *** (Регистр.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Периодичность.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.Периодичность CustomAttributes)

        // *** End programmer edit section *** (Регистр.Периодичность CustomAttributes)
        [StrLen(255)]
        public virtual string Периодичность
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.Периодичность Get start)

                // *** End programmer edit section *** (Регистр.Периодичность Get start)
                string result = this.fПериодичность;
                // *** Start programmer edit section *** (Регистр.Периодичность Get end)

                // *** End programmer edit section *** (Регистр.Периодичность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.Периодичность Set start)

                // *** End programmer edit section *** (Регистр.Периодичность Set start)
                this.fПериодичность = value;
                // *** Start programmer edit section *** (Регистр.Периодичность Set end)

                // *** End programmer edit section *** (Регистр.Периодичность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрE", typeof(IIS.7.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрL", typeof(IIS.7.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрСведенийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрСведенийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрСведенийE", typeof(IIS.7.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрСведенийL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрСведенийL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрСведенийL", typeof(IIS.7.Регистр));
                }
            }
        }
    }
}
