//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "Фамилия as \'Фамилия\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Отчество as \'Отчество\'",
            "Имя as \'Имя\'"})]
    [View("СотрудникL", new string[] {
            "Фамилия as \'Фамилия\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Отчество as \'Отчество\'",
            "Имя as \'Имя\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private int fСерияПаспорта;
        
        private string fОтчество;
        
        private int fКодСотрудника;
        
        private int fНомерПаспорта;
        
        private int fКодДолжности;
        
        private string fИмя;
        
        private string fТабНомер;
        
        private IIS.7.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Имя Get start)

                // *** End programmer edit section *** (Сотрудник.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Сотрудник.Имя Get end)

                // *** End programmer edit section *** (Сотрудник.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Имя Set start)

                // *** End programmer edit section *** (Сотрудник.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Сотрудник.Имя Set end)

                // *** End programmer edit section *** (Сотрудник.Имя Set end)
            }
        }
        
        /// <summary>
        /// КодДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.КодДолжности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.КодДолжности CustomAttributes)
        public virtual int КодДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.КодДолжности Get start)

                // *** End programmer edit section *** (Сотрудник.КодДолжности Get start)
                int result = this.fКодДолжности;
                // *** Start programmer edit section *** (Сотрудник.КодДолжности Get end)

                // *** End programmer edit section *** (Сотрудник.КодДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.КодДолжности Set start)

                // *** End programmer edit section *** (Сотрудник.КодДолжности Set start)
                this.fКодДолжности = value;
                // *** Start programmer edit section *** (Сотрудник.КодДолжности Set end)

                // *** End programmer edit section *** (Сотрудник.КодДолжности Set end)
            }
        }
        
        /// <summary>
        /// КодСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.КодСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.КодСотрудника CustomAttributes)
        public virtual int КодСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.КодСотрудника Get start)

                // *** End programmer edit section *** (Сотрудник.КодСотрудника Get start)
                int result = this.fКодСотрудника;
                // *** Start programmer edit section *** (Сотрудник.КодСотрудника Get end)

                // *** End programmer edit section *** (Сотрудник.КодСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.КодСотрудника Set start)

                // *** End programmer edit section *** (Сотрудник.КодСотрудника Set start)
                this.fКодСотрудника = value;
                // *** Start programmer edit section *** (Сотрудник.КодСотрудника Set end)

                // *** End programmer edit section *** (Сотрудник.КодСотрудника Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.НомерПаспорта CustomAttributes)
        public virtual int НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.НомерПаспорта Get start)

                // *** End programmer edit section *** (Сотрудник.НомерПаспорта Get start)
                int result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (Сотрудник.НомерПаспорта Get end)

                // *** End programmer edit section *** (Сотрудник.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.НомерПаспорта Set start)

                // *** End programmer edit section *** (Сотрудник.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (Сотрудник.НомерПаспорта Set end)

                // *** End programmer edit section *** (Сотрудник.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Отчество CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Отчество Get start)

                // *** End programmer edit section *** (Сотрудник.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Сотрудник.Отчество Get end)

                // *** End programmer edit section *** (Сотрудник.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Отчество Set start)

                // *** End programmer edit section *** (Сотрудник.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Сотрудник.Отчество Set end)

                // *** End programmer edit section *** (Сотрудник.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.СерияПаспорта CustomAttributes)
        public virtual int СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.СерияПаспорта Get start)

                // *** End programmer edit section *** (Сотрудник.СерияПаспорта Get start)
                int result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (Сотрудник.СерияПаспорта Get end)

                // *** End programmer edit section *** (Сотрудник.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.СерияПаспорта Set start)

                // *** End programmer edit section *** (Сотрудник.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (Сотрудник.СерияПаспорта Set end)

                // *** End programmer edit section *** (Сотрудник.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// ТабНомер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ТабНомер CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ТабНомер CustomAttributes)
        [StrLen(255)]
        public virtual string ТабНомер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ТабНомер Get start)

                // *** End programmer edit section *** (Сотрудник.ТабНомер Get start)
                string result = this.fТабНомер;
                // *** Start programmer edit section *** (Сотрудник.ТабНомер Get end)

                // *** End programmer edit section *** (Сотрудник.ТабНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ТабНомер Set start)

                // *** End programmer edit section *** (Сотрудник.ТабНомер Set start)
                this.fТабНомер = value;
                // *** Start programmer edit section *** (Сотрудник.ТабНомер Set end)

                // *** End programmer edit section *** (Сотрудник.ТабНомер Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Фамилия Get start)

                // *** End programmer edit section *** (Сотрудник.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Сотрудник.Фамилия Get end)

                // *** End programmer edit section *** (Сотрудник.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Фамилия Set start)

                // *** End programmer edit section *** (Сотрудник.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Сотрудник.Фамилия Set end)

                // *** End programmer edit section *** (Сотрудник.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.7.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Get start)

                // *** End programmer edit section *** (Сотрудник.Должности Get start)
                IIS.7.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудник.Должности Get end)

                // *** End programmer edit section *** (Сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Set start)

                // *** End programmer edit section *** (Сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудник.Должности Set end)

                // *** End programmer edit section *** (Сотрудник.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.7.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.7.Сотрудник));
                }
            }
        }
    }
}
